routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('blog/home');
// });


Route::get('/', 'PostController@publicHome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('posts', 'PostController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Auth;       
use Illuminate\Http\Request;

class PostController extends Controller
{

    public function publicHome(){
        $posts = Post::paginate(6);

        return view('blog/home', ['posts'=>$posts]);
    }   
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $loggedInUserId =  Auth::id();
        $posts = Post::all()->where('user_id', $loggedInUserId);
       
        return view('adminPanel/home', ['posts'=>$posts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('adminPanel/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $post = new Post;
        $postTitle = $request->title;
        $postSubTitle = $request->subtitle;
        $postBody = $request->body;  
        //$post->user_id = Auth::user()->id;
        $postUserId = Auth::id(); 

        $post->user_id = $postUserId;
        $post->title = $postTitle;
        $post->title = $postSubTitle;
        $post->body = $postBody;

        $post->save();

        return redirect()->route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $post = Post::find($id);

         $data = array(
             'id' => $id,
             'post'=> $post
         );

         return view('blog.viewPost' ,$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);

        return view('adminPanel.edit', ['post'=>$post]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::find($id);

        if (isset($request->title)){
            $post->title = $request->title;
        }
        if (isset($request->subtitle)){
            $post->subtitle = $request->subtitle;
        }

        if (isset($request->body)){
            $post->body = $request->body;
        }

        $post->save();

        if (isset($request->editForm)){
            return redirect()->route('posts.index');
        }else{
           return redirect()->route('posts.show', ['id'=>$id]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);

        $post->delete();

        return redirect()->route('posts.index');
    }
}

resources/views/adminPanel/create.blade.php
@extends('layouts.app')

@section('title', 'Add New Post')

@section('content')


<div class="container my-9">
    
    <form action="{{ route('posts.store') }}" method="POST" role="form">
        {{ csrf_field() }}
        <legend>Add New Post</legend>
    
        <div class="form-group">
            <label for="">Title:</label>
            <input type="text" class="form-control" name="title" id="" placeholder="Input field">
        </div>

        <div class="form-group">
            <label for="">Subtitle:</label>
            <input type="text" class="form-control" name="subtitle" id="" placeholder="Input field">
        </div>

        <div class="form-group">
            <label for="">Content:</label>
            <textarea class="form-control" name="body" id="" placeholder="Input field"></textarea>
        </div>

        
        <button type="submit" class="btn btn-primary">Submit</button>
        
        <a class="btn btn-warning" href="{{ route('posts.index')}}" role="button">Go back</a>
        
    </form>
    
</div>


@endsection()

resources/views/adminPanel/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Post #' . $post->id)

@section('content')


<div class="container my-9">
    
    <form action="{{ route('posts.update', ['id'=>$post->id]) }}" method="POST" role="form">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="PUT">
        
        <legend>Edit Post # {{ $post->id }}</legend>
    
        <div class="form-group">
            <label for="">Title:</label>
            <input type="text" class="form-control" name="title" id="" placeholder="Input field" value="{{ $post->title }}">
        </div>

        <div class="form-group">
            <label for="">Sub Title:</label>
            <input type="text" class="form-control" name="subtitle" id="" placeholder="Input field" value="{{ $post->subtitle }}">
        </div>

        <div class="form-group">
            <label for="">Content:</label>
            <textarea class="form-control" name="body" id="" placeholder="Input field">{{ $post->body }}</textarea>
        </div>

        <input type="hidden" name="editForm" value="editForm">
        <button type="submit" class="btn btn-primary">Submit</button>
        
        <a class="btn btn-warning" href="{{ route('posts.index')}}" role="button">Go back</a>
        
    </form>
    
</div>


@endsection()

resources/views/adminPanel/home.blade.php
@extends('layouts.app')

@section('title', 'Manage Post Admin')


@section('content')

<div class="container my-9">
  <h1 class="m-3">Admin Panel</h1>
    <a href="{{ route('posts.create') }}" class="btn btn-sm btn-primary float-right m-3">Add new blog post</a><br>
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Sub Title</th>
                <th>Content</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
        @foreach($posts as $post)
            <tr>
                <td>{{ $post->id  }}</td>
                <td>{{ $post->title  }}</td>
                <td>{{ $post->subtitle  }}</td>
                <td>{{ $post->body  }}</td>
                <td>
                   <a class="btn btn-sm btn-warning" href="{{ route('posts.edit',['id'=>$post->id]) }}" role="button">Edit Post</a>    
                </td>
                <td>
                    <form action="{{ route('posts.destroy', ['id'=>$post->id]) }}" method="post">
                    {{ csrf_field() }}
                        <input type="hidden" name="_method" value="DELETE">
                        <input class="btn btn-sm btn-danger" type="submit" value="Delete">
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
</div>
@endsection

resources/views/blog/home.blade.php
@extends('layouts.app')

@section('content')
 <!-- Page Content -->
 <div class="container bg-white">

<!-- Page Heading -->
<h1 class="my-5 py-5">Produckte</h1>
<hr>
<ul class="breadcrumb">
  <li><i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i></i> &nbsp;<a href="#"> Home </a>&nbsp;</li>
  <li><i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> &nbsp;<a href="#"> Warme/Kalte </a>&nbsp;</li>
  <li><i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> &nbsp;<a href="#"> Automatikfilter </a>&nbsp;</li>
</ul>
<!-- Project One -->
<div class="row">
@foreach($posts as $post)
  <div class="col-md-3 my-4">
    <a href="#">
      <img class="img-responsive" src="{{asset('images/produkt.jpg')}}" alt="">
    </a>
  </div>
  <div class="col-md-8 my-4">
    <h3>{{ $post->title }}</h3>
    <h6> {{ $post->subtitle }}</h6>
    <p>{{ $post->body }}</p>
    <a class="btn btn-primary float-right" href="{{ route('posts.show',['id'=>$post->id]) }}">Mehr Erfahren ></a>
  </div>
  @endforeach  
</div>
<!-- /.row -->

<hr>

</div>
<!-- /.container -->
    <!-- <div class="container">
        <h1>The LRMG Blog</h1>
        <div class="row">  
            @foreach($posts as $post)
                <div class="col-md-12 col-lg-12">
                        <div class="p-3 mb-2 bg-primary text-white">
                            <h2>{{ $post->title }}</h2>
                            <hr>
                            <h6><strong>Post Created At:</strong> {{ date('F d, Y', strtotime($post->created_at)) }}</h6>
                            <p>{{ $post->body }}</p>
                            <a class="btn btn-sm btn-warning" href="{{ route('posts.show',['id'=>$post->id]) }}" role="button">View all</a>    
                        </div>
                </div>
            @endforeach    
        
        </div>
        <div class="text-center">{{ $posts->links() }}</div>
    </div> -->


@endsection

resources/views/blog/viewPost.blade.php
@extends('layouts.publicHomePageTemplate')

@section('title', 'View Post #' . $id)
  
@section('content')   

<div class="container my-9"">
    <h2>{{ $post->title  }}</h2>
    <h6><strong>Post Created At:</strong> {{ date('F d, Y', strtotime($post->created_at)) }}</h6>
    <img class="img-responsive" src="{{asset('images/produkt.jpg')}}" alt="">
    <p>{{ $post->body }}</p>    
    <a class="btn btn-sm btn-primary" href="{{ url('/') }}" role="button">Back to home</a>
       
</div>

    
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'EIG CRUSTAG') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    
      
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
      <div class="container">
          <hr>
        <a class="navbar-brand" href="{{url('/')}}"><img src="{{asset('images/logo.png')}}" alt="logo"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
          @guest 
            <li class="nav-item nav-border">
            <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
            </a>
            </li>
            <li class="nav-item nav-border">
            <a class="nav-link" href="#">Uber Uns</a>
            </li>
            <li class="nav-item nav-border active">
            <a class="nav-link" href="#">Produkte</a>
            </li>
            <li class="nav-item nav-border">
            <a class="nav-link" href="#">Referenzen</a>
            </li>
            &nbsp;&nbsp;&nbsp;
            <li class="nav-item navbar-font-lan">
              <a class="nav-link" href="#">DE / FR</a>
            </li>
            @else
            <li><a class="nav-link" href="{{ route('posts.index') }}">Manage posts</a></li>
            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    {{ Auth::user()->name }} <span class="caret"></span>
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ route('logout') }}"
                    onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
        @endguest
          </ul>
        </div>
      </div>
    </nav>
        <main class="py-5">
            @yield('content')
        </main>
    
     <!-- Footer -->
     <footer class="py-5 bg-white">
      <div class="container">
       
       <div class="row">
           
           <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
           © Eig Crustag 2018<br>
           Impressum
           </div>
           
           <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
               <h5>Buro Baar ZG</h3>
               <ul class="list-unstyled footer-ul-list-none">
                   <li><i class="fa fa-mobile" aria-hidden="true"></i>(Tel)+41 22735 95 00</li>
                   <li><i class="fa fa-print" aria-hidden="true"></i>(Fax)+41 786 96 00</li>
                   <li><i class="fa fa-map-marker" aria-hidden="true"></i>Route de Frontenex 120</li>
               </ul>
           </div>
           
           <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
               <h5>Bureau Geneve</h3>
               <ul class="list-unstyled footer-ul-list-none">
                   <li><i class="fa fa-mobile" aria-hidden="true"></i>(Tel)+41 22735 95 00</li>
                   <li><i class="fa fa-print" aria-hidden="true"></i>(Fax)+41 786 96 00</li>
                   <li><i class="fa fa-map-marker" aria-hidden="true"></i>Route de Frontenex 120</li>
               </ul>
           </div>
           
       </div>
       
      </div>
      <!-- /.container -->
    </footer>
</body>
</html>

resources/views/layouts/publicHomePageTemplate.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <h1>@yield('title')</h1>
  
  <div class="row">
      
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="p-3 mb-2 bg-dark text-white">
                <h2>Post 1</h2>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Incidunt dicta dignissimos nam inventore aut? Facere dolor voluptatum magni deleniti nulla quasi laboriosam animi et officia repellat sunt enim, aperiam recusandae.</p>     
            </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="p-3 mb-2 bg-dark text-white">
                <h2>Post 2</h2>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Incidunt dicta dignissimos nam inventore aut? Facere dolor voluptatum magni deleniti nulla quasi laboriosam animi et officia repellat sunt enim, aperiam recusandae.</p>     
            </div>
      </div>
      
  </div>
  
</div>
@endsection